version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    env_file:
      - ./.env.front

  backend:
    image: python:3.11-alpine
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5000:5000
    command: python3 /usr/src/app/main.py

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.db

volumes:
  postgres-data:
